# pull the official base image
FROM node:alpine as builder
# set working direction
WORKDIR /app
# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH
# install application dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm i --legacy-peer-deps
# add app
COPY . ./
# build
RUN npm run build-prod

FROM nginx:1.15-alpine as runner
COPY --from=builder /app/build/ /usr/share/nginx/html